# Знакомство с библиотекой Pandas. Группировка данных

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('bike_sharing_demand.csv', sep = ',')

In [3]:
df.head(3)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32

In [9]:
df.groupby(['casual'])

In [8]:
df.groupby(['casual']).groups

{0: [4, 5, 29, 30, 31, 45, 46, 47, 48, 49, 50, 51, 67, 69, 70, 71, 72, 73, 74, 89, 92, 93, 94, 95, 96, 97, 115, 116, 117, 118, 119, 120, 121, 135, 140, 141, 142, 158, 164, 165, 166, 167, 169, 170, 181, 184, 186, 187, 188, 189, 190, 191, 193, 194, 195, 205, 208, 211, 212, 214, 215, 219, 223, 232, 234, 235, 236, 237, 250, 251, 252, 255, 256, 257, 258, 259, 260, 263, 266, 267, 270, 274, 278, 279, 280, 281, 282, 283, 284, 297, 298, 299, 301, 302, 303, 304, 305, 306, 307, 309, ...], 1: [7, 8, 25, 26, 32, 42, 52, 53, 68, 88, 90, 98, 113, 114, 136, 157, 160, 161, 162, 168, 183, 185, 192, 204, 206, 210, 213, 227, 229, 230, 249, 253, 254, 268, 272, 275, 276, 277, 296, 300, 323, 327, 330, 331, 332, 353, 372, 373, 376, 395, 401, 402, 403, 407, 409, 411, 414, 415, 417, 430, 453, 460, 461, 462, 467, 475, 478, 484, 497, 498, 519, 522, 523, 525, 527, 535, 567, 572, 573, 576, 577, 578, 598, 607, 614, 615, 622, 627, 630, 638, 651, 652, 653, 665, 667, 670, 671, 685, 694, 708, ...], 2: [6, 27, 28, 75, 76, 77, 87, 91, 125, 139, 159, 172, 182, 196, 209, 216, 218, 220, 224, 231, 233, 238, 243, 246, 271, 273, 286, 287, 290, 293, 308, 312, 322, 325, 333, 334, 370, 391, 398, 416, 427, 431, 439, 441, 442, 452, 464, 468, 487, 489, 495, 499, 506, 520, 521, 542, 546, 548, 556, 608, 609, 632, 633, 637, 661, 663, 666, 684, 686, 689, 690, 695, 696, 707, 717, 742, 765, 767, 790, 804, 807, 831, 832, 835, 875, 884, 897, 900, 908, 1000, 1013, 1048, 1063, 1106, 1107, 1115, 1142, 1166, 1205, 1226, ...], 3: [0, 3, 21, 65, 66, 86, 99, 109, 112, 122, 124, 133, 134, 156, 163, 179, 202, 228, 239, 240, 241, 245, 261, 262, 264, 265, 289, 291, 295, 316, 319, 324, 350, 357, 380, 393, 399, 438, 443, 446, 448, 449, 466, 473, 477, 501, 508, 509, 511, 518, 524, 533, 534, 545, 551, 581, 593, 594, 603, 610, 616, 619, 634, 655, 660, 688, 691, 734, 735, 777, 778, 808, 809, 811, 855, 859, 899, 901, 904, 922, 925, 946, 947, 1011, 1012, 1016, 1025, 1026, 1049, 1066, 1091, 1104, 1135, 1137, 1160, 1211, 1249, 1254, 1347, 1374, ...], 4: [24, 37, 101, 107, 108, 137, 138, 180, 197, 203, 217, 222, 225, 226, 242, 247, 288, 294, 310, 313, 317, 321, 349, 379, 389, 392, 422, 426, 428, 447, 456, 463, 474, 485, 490, 491, 492, 496, 500, 549, 571, 587, 596, 606, 612, 613, 626, 628, 631, 641, 654, 658, 662, 664, 672, 706, 715, 828, 874, 876, 896, 923, 933, 971, 973, 1005, 1006, 1087, 1089, 1101, 1111, 1136, 1143, 1163, 1183, 1189, 1204, 1207, 1252, 1258, 1277, 1306, 1330, 1348, 1439, 1449, 1491, 1498, 1514, 1590, 1595, 1620, 1621, 1640, 1693, 1702, 1706, 1708, 1784, 1807, ...], 5: [2, 43, 78, 103, 110, 132, 153, 171, 176, 178, 200, 207, 221, 269, 285, 292, 314, 318, 347, 418, 419, 425, 444, 450, 465, 476, 493, 494, 510, 526, 538, 544, 568, 569, 570, 590, 591, 650, 674, 687, 697, 712, 733, 755, 768, 779, 788, 802, 826, 872, 944, 968, 974, 975, 980, 999, 1028, 1039, 1046, 1073, 1076, 1108, 1182, 1203, 1276, 1278, 1301, 1353, 1373, 1432, 1467, 1473, 1515, 1539, 1542, 1562, 1633, 1664, 1683, 1684, 1685, 1705, 1755, 1850, 1858, 1859, 1860, 1924, 2042, 2067, 2093, 2114, 2118, 2377, 2378, 2451, 2503, 2504, 2693, 2717, ...], 6: [19, 100, 104, 123, 126, 198, 244, 248, 311, 344, 345, 348, 369, 388, 429, 486, 543, 579, 582, 592, 595, 611, 656, 659, 710, 732, 770, 789, 853, 860, 889, 920, 940, 941, 943, 957, 970, 972, 1100, 1132, 1162, 1431, 1434, 1540, 1587, 1596, 1618, 1623, 1658, 1659, 1694, 1698, 1700, 1707, 1733, 1782, 1857, 1972, 1994, 2020, 2024, 2066, 2072, 2139, 2189, 2197, 2210, 2452, 2523, 2552, 2692, 2834, 2858, 2875, 2909, 2955, 3007, 3053, 3344, 3386, 3560, 3626, 3633, 3704, 3728, 3788, 3789, 3803, 3893, 3965, 4033, 4037, 4062, 4102, 4150, 4175, 4229, 4507, 4604, 4632, ...], 7: [33, 40, 54, 79, 106, 111, 151, 155, 174, 368, 382, 390, 421, 424, 445, 471, 472, 547, 557, 580, 584, 604, 605, 635, 676, 683, 743, 759, 792, 812, 892, 910, 935, 937, 1064, 1131, 1158, 1206, 1275, 1393, 1396, 1402, 1504, 1523, 1563, 1565, 1588, 1608, 1630, 1657, 1682, 1690, 1714, 1780, 1785, 1832, 2095, 2112, 2163, 2185, 2240, 2264, 2283, 2359, 2426, 2505, 2528, 2599, 2670, 2671, 2862, 2885, 2911, 3027, 3031, 3123, 3146, 3195, 3214, 3215, 3224, 3248, 3363, 3482, 3603, 3605, 3609, 3761, 3775, 3776, 3886, 3887, 3917, 3957, 3960, 3986, 4151, 4251, 4253, 4338, ...], 8: [1, 9, 58, 64, 129, 143, 144, 173, 177, 199, 358, 381, 470, 512, 516, 540, 586, 617, 629, 673, 744, 756, 825, 827, 836, 886, 888, 898, 912, 919, 1077, 1168, 1181, 1331, 1371, 1372, 1392, 1440, 1452, 1474, 1509, 1522, 1609, 1660, 1681, 1756, 1775, 1781, 1873, 1899, 1904, 1923, 1929, 1947, 1953, 2018, 2186, 2235, 2288, 2309, 2337, 2450, 2501, 2502, 2522, 2570, 2600, 2624, 2741, 2766, 2788, 2912, 2932, 3128, 3320, 3506, 3530, 3778, 3819, 3958, 4058, 4075, 4078, 4110, 4149, 4333, 4354, 4364, 4368, 4463, 4504, 4505, 4517, 4566, 4590, 4603, 4746, 4801, 4822, 4910, ...], 9: [18, 39, 61, 63, 82, 131, 146, 149, 150, 152, 154, 315, 351, 383, 488, 513, 515, 589, 636, 682, 709, 745, 861, 873, 921, 969, 1050, 1062, 1109, 1144, 1180, 1225, 1251, 1262, 1344, 1394, 1427, 1433, 1490, 1513, 1598, 1606, 1695, 1701, 1752, 1779, 1805, 1806, 1872, 1925, 1969, 2000, 2017, 2048, 2233, 2234, 2355, 2480, 2500, 2594, 2648, 2716, 2816, 2859, 2978, 3054, 3124, 3200, 3204, 3293, 3340, 3368, 3387, 3437, 3578, 3628, 3753, 3823, 3847, 4029, 4063, 4101, 4158, 4174, 4301, 4331, 4339, 4340, 4392, 4422, 4567, 4723, 4724, 4737, 4739, 4743, 4749, 4758, 4775, 4800, ...], 10: [41, 56, 85, 105, 384, 423, 469, 517, 536, 537, 585, 746, 766, 772, 801, 854, 885, 893, 895, 934, 936, 959, 961, 996, 1008, 1051, 1081, 1083, 1088, 1119, 1133, 1161, 1212, 1214, 1235, 1237, 1248, 1345, 1355, 1377, 1419, 1420, 1426, 1501, 1508, 1536, 1607, 1632, 1665, 1922, 1949, 2209, 2257, 2336, 2384, 2456, 2475, 2476, 2477, 2721, 2860, 2930, 3052, 3080, 3104, 3291, 3338, 3441, 3489, 3681, 3934, 4030, 4124, 4250, 4318, 4351, 4355, 4367, 4374, 4446, 4462, 4494, 4589, 4628, 4630, 4675, 4744, 4750, 4828, 4909, 4928, 4981, 5008, 5014, 5056, 5078, 5083, 5105, 5151, 5175, ...], 11: [20, 22, 36, 44, 55, 59, 62, 128, 366, 420, 539, 583, 730, 753, 769, 773, 798, 823, 850, 911, 981, 997, 1027, 1038, 1052, 1065, 1075, 1086, 1134, 1159, 1167, 1250, 1282, 1307, 1332, 1466, 1512, 1586, 1597, 1641, 1731, 1753, 1777, 2113, 2117, 2144, 2207, 2232, 2258, 2312, 2354, 2360, 2576, 2672, 2696, 2720, 2810, 2840, 2864, 2888, 2953, 3170, 3194, 3216, 3225, 3297, 3505, 3705, 3732, 3737, 3785, 3956, 4010, 4056, 4126, 4134, 4271, 4337, 4378, 4418, 4487, 4503, 4533, 4541, 4578, 4582, 4631, 4651, 4686, 4829, 4973, 5040, 5141, 5142, 5168, 5182, 5183, 5296, 5345, 5352, ...], 12: [10, 80, 102, 127, 130, 175, 386, 675, 679, 720, 754, 803, 829, 894, 958, 993, 994, 998, 1010, 1085, 1259, 1333, 1346, 1438, 1511, 1538, 1541, 1561, 1569, 1593, 1622, 1625, 1709, 1737, 1849, 2040, 2041, 2184, 2198, 2402, 2649, 2884, 3032, 3176, 3313, 3410, 3537, 3575, 3585, 3598, 3740, 3742, 3800, 3863, 3870, 4077, 4112, 4125, 4278, 4294, 4439, 4565, 4568, 4569, 4698, 4721, 4770, 4774, 4798, 4884, 4902, 4944, 4950, 4951, 4984, 4986, 4999, 5010, 5037, 5047, 5070, 5071, 5084, 5152, 5153, 5184, 5224, 5239, 5272, 5289, 5294, 5322, 5326, 5339, 5341, 5342, 5367, 5408, 5420, 5480, ...], 13: [57, 201, 385, 566, 698, 794, 887, 890, 909, 938, 962, 1121, 1191, 1239, 1322, 1378, 1465, 1499, 1727, 1864, 1898, 2001, 2116, 2162, 2169, 2408, 2432, 2546, 2668, 2765, 2820, 2841, 2960, 2993, 3242, 3314, 3435, 3460, 3555, 3741, 4008, 4054, 4111, 4123, 4342, 4365, 4379, 4416, 4417, 4498, 4508, 4531, 4555, 4662, 4700, 4772, 4799, 4805, 4845, 4886, 4888, 4998, 5009, 5080, 5081, 5094, 5103, 5223, 5243, 5270, 5321, 5340, 5343, 5410, 5431, 5444, 5463, 5531, 5564, 5621, 5623, 5648, 5654, 5670, 5697, 5843, 5912, 5916, 5964, 6010, 6011, 6033, 6050, 6084, 6131, 6200, 6221, 6268, 6278, 6434, ...], 14: [60, 343, 367, 541, 680, 749, 771, 776, 791, 793, 824, 1079, 1123, 1219, 1224, 1369, 1696, 1732, 1848, 2049, 2099, 2193, 2208, 2256, 2280, 2307, 2545, 2669, 2689, 3002, 3008, 3057, 3169, 3268, 3269, 3273, 3290, 3385, 3480, 3604, 3754, 3764, 3781, 3805, 3894, 4031, 4087, 4224, 4231, 4295, 4328, 4436, 4438, 4496, 4509, 4601, 4687, 4697, 4782, 4869, 4903, 5013, 5240, 5291, 5315, 5319, 5320, 5551, 5561, 5574, 5589, 5653, 5696, 5720, 5721, 5742, 5819, 6008, 6054, 6081, 6108, 6111, 6364, 6404, 6411, 6458, 6532, 6665, 6667, 6672, 6839, 6935, 6953, 6997, 7023, 7031, 7071, 7202, 7214, 7270, ...], 15: [17, 23, 84, 336, 342, 514, 558, 731, 775, 817, 818, 820, 838, 967, 982, 1029, 1078, 1082, 1120, 1124, 1125, 1335, 1463, 1476, 1594, 1629, 1730, 1764, 1863, 2092, 2111, 2282, 2414, 2449, 2643, 2691, 2787, 3177, 3393, 3434, 3625, 3652, 3720, 3729, 3738, 3782, 3843, 3845, 3910, 4014, 4122, 4182, 4248, 4326, 4329, 4363, 4390, 4470, 4543, 4581, 4591, 4602, 4759, 4907, 4974, 5057, 5082, 5169, 5180, 5191, 5201, 5241, 5392, 5411, 5419, 5423, 5454, 5649, 5652, 5723, 5725, 5749, 5773, 5835, 5865, 5883, 5908, 5933, 5934, 6031, 6035, 6055, 6082, 6107, 6202, 6276, 6279, 6280, 6338, 6363, ...], 16: [34, 147, 588, 751, 814, 848, 852, 960, 995, 1032, 1057, 1300, 1342, 1585, 1600, 1667, 1680, 1697, 1786, 1804, 1809, 1825, 1881, 1897, 1977, 1993, 2065, 2073, 2098, 2253, 2332, 2601, 2644, 3028, 3056, 3075, 3369, 3436, 3459, 3731, 3733, 3779, 3817, 3824, 3842, 3885, 3966, 4015, 4097, 4099, 4116, 4119, 4336, 4353, 4376, 4461, 4519, 4521, 4650, 4699, 4712, 4885, 4936, 5000, 5077, 5079, 5148, 5244, 5415, 5424, 5554, 5587, 5588, 5869, 5896, 5918, 5956, 6109, 6154, 6277, 6342, 6362, 6403, 6460, 6463, 6493, 6567, 6624, 6711, 6769, 7007, 7009, 7036, 7056, 7126, 7262, 7648, 7746, 7822, 7966, ...], 17: [83, 678, 729, 795, 839, 942, 965, 1080, 1201, 1260, 1274, 1334, 1417, 1435, 1451, 1500, 1547, 1631, 1833, 1870, 1871, 1948, 2005, 2035, 2138, 2171, 2216, 2593, 2667, 2769, 3033, 3099, 3267, 3384, 3417, 3623, 3651, 3653, 3676, 3700, 3780, 3942, 4064, 4100, 4223, 4316, 4377, 4393, 4398, 4495, 4500, 4518, 4570, 4605, 4674, 4736, 4769, 4844, 4887, 4935, 4979, 5034, 5036, 5073, 5104, 5271, 5292, 5314, 5407, 5417, 5462, 5562, 5651, 5703, 5795, 5917, 5941, 6007, 6227, 6304, 6437, 6530, 6531, 6533, 6601, 6615, 6744, 6783, 6830, 7120, 7438, 7479, 7550, 7569, 7893, 7913, 8038, 8126, 8196, 8247, ...], 18: [81, 335, 681, 800, 813, 815, 822, 862, 891, 939, 1007, 1074, 1084, 1122, 1128, 1223, 1241, 1247, 1271, 1284, 1336, 1379, 1418, 1464, 1489, 1560, 1643, 2029, 2075, 2091, 2137, 2161, 2217, 2308, 2361, 2401, 2425, 2439, 2441, 2481, 2604, 2666, 2984, 3106, 3292, 3321, 3513, 3554, 3576, 3599, 3601, 3602, 3730, 3736, 3763, 3818, 3985, 4171, 4198, 4254, 4330, 4362, 4380, 4391, 4530, 4577, 4663, 4672, 4722, 4734, 4738, 4783, 4821, 4857, 4929, 5001, 5002, 5075, 5268, 5387, 5432, 5695, 5724, 5915, 5932, 6080, 6127, 6325, 6494, 6626, 6705, 6856, 7030, 7122, 7174, 7189, 7248, 7390, 7534, 7863, ...], 19: [38, 148, 721, 750, 816, 849, 851, 916, 1030, 1037, 1130, 1238, 1273, 1416, 1437, 1488, 1502, 1535, 1602, 1655, 1729, 1765, 1766, 1768, 1778, 1862, 1888, 1930, 2241, 2265, 2498, 2499, 2553, 2555, 2569, 2740, 2786, 2809, 2907, 2929, 2936, 3145, 3201, 3206, 3337, 3362, 3458, 3561, 3699, 3920, 3925, 4052, 4088, 4113, 4136, 4137, 4199, 4302, 4387, 4571, 4592, 4627, 4638, 4710, 4745, 4795, 4819, 4868, 4934, 5003, 5038, 5149, 5215, 5295, 5388, 5414, 5533, 5534, 5607, 5790, 5797, 6006, 6034, 6101, 6203, 6341, 6400, 6507, 6508, 6568, 6664, 6704, 6879, 6912, 6960, 7247, 7295, 7311, 7476, 7527, ...], 20: [35, 145, 799, 913, 1263, 1320, 1370, 1738, 1751, 1762, 1774, 1837, 1883, 1905, 2415, 2435, 2436, 2544, 2690, 2715, 2833, 2952, 2977, 3081, 3466, 3529, 3541, 3553, 3577, 3677, 3719, 3918, 3933, 3954, 3982, 4038, 4140, 4173, 4183, 4184, 4249, 4356, 4361, 4389, 4499, 4523, 4542, 4673, 4761, 4911, 4965, 4980, 5007, 5039, 5266, 5385, 5441, 5455, 5558, 5792, 5820, 5894, 5963, 6004, 6039, 6315, 6420, 6441, 6461, 6464, 6484, 6518, 6566, 6578, 6648, 6787, 6902, 7032, 7055, 7121, 7150, 7200, 7238, 7567, 7672, 7814, 7846, 7847, 8183, 8278, 8414, 8681, 9231, 9256, 9262, 9286, 9469, 9563, 9707, 9886, ...], 21: [337, 339, 387, 677, 774, 871, 915, 1033, 1061, 1127, 1146, 1221, 1453, 1537, 1559, 1604, 1642, 1644, 1666, 1728, 1810, 1992, 2026, 2027, 2051, 2642, 2889, 2951, 3077, 3098, 3168, 3210, 3312, 3682, 3762, 3862, 3872, 3968, 4009, 4041, 4057, 4065, 4501, 4502, 4520, 4580, 4649, 4666, 4689, 4713, 4717, 4720, 4853, 4859, 5361, 5585, 5750, 5767, 5791, 5868, 6270, 6467, 6517, 6555, 6602, 6673, 6759, 6927, 6952, 6996, 7261, 7284, 7286, 7310, 7406, 7414, 7428, 7551, 7744, 7889, 7918, 8080, 8125, 8153, 8206, 8638, 8639, 8758, 8832, 8872, 8991, 9014, 9042, 9084, 9085, 9190, 9214, 9492, 9590, 9755, ...], 22: [362, 364, 966, 1009, 1156, 1215, 1222, 1243, 1296, 1356, 1455, 1599, 1654, 1656, 1761, 1865, 1866, 1867, 1919, 1946, 2086, 2160, 2170, 2333, 2448, 2577, 2579, 2793, 2943, 3105, 3131, 3192, 3361, 3409, 3504, 3634, 3650, 3739, 3841, 3953, 4118, 4138, 4148, 4220, 4293, 4357, 4388, 4415, 4485, 4547, 4711, 4833, 4930, 5006, 5024, 5409, 5586, 5606, 5702, 5796, 5891, 5898, 5937, 5982, 6103, 6291, 6323, 6326, 6466, 6614, 6625, 6712, 6984, 7008, 7043, 7382, 7511, 7528, 7529, 7745, 7775, 7813, 7957, 7974, 8174, 8319, 8366, 8558, 9063, 9278, 9358, 9490, 9647, 9684, 10042, 10151, 10273, 10295, 10327, 10352, ...], 23: [359, 361, 365, 1129, 1179, 1202, 1213, 1218, 1240, 1261, 1454, 1475, 1626, 1763, 1799, 1978, 2183, 2254, 2281, 2330, 2385, 2460, 2739, 2987, 2994, 3009, 3026, 3203, 3249, 3298, 3944, 3967, 4073, 4222, 4375, 4483, 4522, 4735, 4768, 4797, 4856, 4867, 5389, 5553, 5598, 5701, 5794, 6124, 6324, 6706, 6708, 7359, 7367, 7449, 7478, 8150, 8566, 8590, 8680, 9349, 9505, 9638, 9695, 9808, 9815, 9902, 9987, 10020, 10043, 10132, 10135, 10175, 10187, 10330, 10356, 10451, 10542, 10560, 10568, 10587, 10620, 10658, 10688, 10760, 10776, 10786, 10880], 24: [565, 705, 1190, 1195, 1197, 1220, 1264, 1283, 1368, 1391, 1404, 1601, 1624, 1834, 1980, 2087, 2090, 2122, 2206, 2306, 2338, 2409, 2497, 2602, 2616, 2817, 2821, 3051, 3153, 3228, 3241, 3288, 3514, 3574, 3658, 3783, 3909, 3932, 4007, 4055, 4185, 4197, 4399, 4573, 4576, 4714, 4718, 4767, 4806, 4818, 5005, 5172, 5174, 5293, 5413, 5698, 5914, 6343, 6399, 6465, 6513, 6639, 6829, 7079, 7103, 7166, 7212, 7337, 7704, 8087, 8518, 8679, 8782, 8806, 8871, 9182, 9191, 9205, 9310, 9334, 9375, 9564, 9681, 9780, 9863, 10066, 10086, 10131, 10304, 10326, 10513, 10538, 10686, 10705, 10726], 25: [752, 1053, 1056, 1126, 1145, 1200, 1272, 1584, 1627, 1679, 1882, 1971, 1990, 2025, 2064, 2085, 2088, 2194, 2249, 2266, 2289, 2353, 2366, 2440, 2457, 2614, 2625, 2674, 2697, 2843, 2970, 3122, 3227, 3239, 3457, 3600, 3848, 3945, 3950, 3955, 4053, 4147, 4255, 4332, 4471, 4544, 4553, 4688, 4820, 5004, 5023, 5440, 5442, 5770, 5890, 5935, 5936, 5983, 6009, 6126, 6302, 6303, 6565, 6738, 6745, 6768, 6854, 6901, 7142, 7199, 7296, 7503, 7568, 7630, 7712, 7942, 7990, 8006, 8055, 8114, 8320, 8342, 8510, 8654, 8662, 8894, 8903, 8950, 9157, 9516, 9640, 9767, 10104, 10174, 10297, 10425, 10472, 10592, 10637, 10712, ...], 26: [11, 338, 722, 797, 819, 837, 1035, 1054, 1059, 1155, 1193, 1236, 1246, 1265, 1298, 1299, 1337, 1678, 1767, 1944, 1981, 2074, 2173, 2195, 2245, 2304, 2331, 2363, 2529, 2612, 3134, 3336, 3542, 3573, 3718, 3871, 3895, 4114, 4117, 4159, 4448, 4549, 4716, 4832, 4855, 4866, 4964, 5386, 5458, 5555, 5793, 5887, 6125, 6487, 6650, 7033, 7067, 7210, 7223, 7271, 7272, 7405, 7622, 7766, 7894, 8014, 8031, 8221, 8351, 8398, 8542, 8678, 8868, 9252, 9372, 9504, 9528, 9729, 9792, 9960, 9961, 10048, 10213, 10215, 10325, 10353, 10496, 10512, 10524, 10535, 10879], 27: [700, 747, 748, 917, 992, 1036, 1192, 1196, 1198, 1216, 1321, 1436, 1459, 1482, 1524, 1886, 1889, 1907, 1921, 2004, 2050, 2145, 2313, 2387, 2400, 2412, 2580, 2874, 2913, 2914, 2963, 2992, 3025, 3111, 3155, 3156, 3274, 3419, 3467, 3515, 3540, 3562, 3807, 3921, 3943, 3991, 4051, 4068, 4074, 4141, 4221, 4230, 4279, 4292, 4317, 4327, 4358, 4386, 4473, 4545, 4719, 4830, 4854, 4860, 4864, 4865, 4933, 5170, 5171, 5390, 5599, 5886, 6105, 6348, 6510, 6519, 6534, 6737, 6840, 7209, 7236, 7285, 7463, 7585, 7743, 7837, 8111, 8151, 8224, 8225, 8254, 8294, 8446, 8534, 8711, 8735, 8833, 8927, 9087, 9168, ...], 28: [559, 727, 1031, 1178, 1570, 1628, 1645, 1773, 1824, 1846, 1954, 1991, 2002, 2009, 2038, 2052, 2146, 2159, 2267, 2362, 2367, 2413, 2417, 2474, 2506, 2626, 2627, 2650, 2842, 2908, 2937, 3076, 3129, 3287, 3360, 3442, 3516, 3647, 3983, 3984, 4067, 4121, 4135, 4142, 4172, 4423, 4484, 4664, 4665, 4690, 4841, 4858, 5200, 5362, 5559, 5743, 5748, 6106, 6398, 6627, 6697, 6888, 7042, 7273, 7336, 7439, 7584, 7678, 8112, 8279, 8736, 8807, 8918, 8941, 9023, 9071, 9089, 9156, 9230, 9250, 9251, 9324, 9373, 9423, 9430, 9468, 9565, 9575, 9663, 9803, 9839, 9924, 9994, 10278, 10305, 10321, 10346, 10450, 10523, 10681, ...], 29: [12, 341, 360, 821, 847, 1055, 1367, 1456, 1477, 1503, 1603, 1750, 1835, 1868, 1918, 1968, 2003, 2016, 2136, 2231, 2247, 2255, 2314, 2329, 2375, 2447, 2458, 2568, 2603, 2844, 2961, 3011, 3132, 3133, 3193, 3202, 3205, 3226, 3266, 3289, 3322, 3394, 3418, 3490, 3552, 3611, 3806, 3840, 3884, 3951, 4039, 4094, 4115, 4186, 4195, 4472, 4626, 4765, 4831, 4840, 4863, 4963, 5074, 5173, 5460, 6368, 6720, 6792, 6936, 7237, 7309, 7361, 7631, 7646, 7798, 7969, 8005, 8102, 8115, 8390, 8489, 8557, 8726, 8965, 9040, 9215, 9300, 9577, 9613, 9664, 9996, 10322, 10543, 10544, 10562, 10591, 10661, 10754, 10807], 30: [699, 702, 728, 918, 963, 1244, 1267, 1338, 1770, 1869, 1884, 1896, 1908, 1945, 2015, 2028, 2182, 2199, 2305, 2442, 2558, 2832, 2845, 2865, 2867, 2868, 2878, 3335, 3345, 3586, 3635, 3649, 3812, 3926, 4066, 4161, 4164, 4219, 4551, 4615, 4668, 4696, 4796, 4842, 5216, 5364, 5366, 5412, 5744, 5940, 6442, 6540, 6674, 6878, 7119, 7249, 7595, 7623, 7671, 7727, 7751, 7799, 7812, 7860, 7934, 7975, 8399, 8400, 8855, 9095, 9144, 9183, 9481, 9576, 9731, 10081, 10112, 10185, 10257, 10275, 10349, 10366, 10378, 10449, 10659, 10730, 10875], 31: [840, 964, 1403, 1548, 1668, 1715, 1812, 1970, 2063, 2076, 2089, 2158, 2172, 2175, 2244, 2252, 2290, 2364, 2399, 2433, 2520, 2592, 2714, 2808, 2818, 2819, 2857, 2882, 2986, 3035, 3130, 3179, 3209, 3395, 3528, 3539, 3587, 3610, 3698, 3716, 3907, 3947, 3952, 4005, 4207, 4303, 4306, 4315, 4482, 4552, 4691, 4715, 4794, 4862, 4931, 4932, 5032, 5033, 5192, 5217, 5772, 5892, 5957, 5988, 6345, 6367, 6388, 6412, 6707, 6709, 6864, 7201, 7224, 7260, 7391, 7823, 7968, 8079, 8246, 8374, 8640, 8867, 9515, 9517, 9730, 9807, 9864, 9935, 9989, 9991, 10007, 10032, 10044, 10065, 10082, 10085, 10107, 10258, 10302, 10488, ...], 32: [701, 1034, 1217, 1266, 1800, 1967, 2039, 2246, 2434, 2482, 2609, 2846, 2856, 2967, 2985, 3012, 3112, 3121, 3181, 3371, 3816, 3839, 3981, 3992, 4040, 4096, 4160, 4162, 4477, 4524, 4546, 4572, 4667, 4692, 4793, 5222, 5363, 5699, 6687, 6951, 7320, 7535, 7912, 7956, 8270, 8303, 8422, 8544, 8591, 8615, 8663, 8703, 8848, 9204, 9467, 9479, 9754, 9888, 10017, 10157, 10222, 10299, 10301, 10785], 33: [340, 1242, 1571, 1796, 1894, 2196, 2268, 2279, 2521, 2556, 2559, 2582, 2585, 2605, 2764, 2823, 2880, 2968, 2988, 3001, 3107, 3135, 3240, 3567, 3597, 3622, 3648, 3674, 3810, 3811, 3814, 3898, 3919, 4069, 4188, 4314, 4414, 4447, 4497, 4574, 4575, 4595, 4693, 4961, 5365, 5456, 5700, 5771, 5889, 5984, 6272, 6389, 6485, 6782, 6806, 6853, 6900, 6974, 7127, 7301, 7564, 7607, 7608, 7621, 7679, 7702, 7911, 8364, 8438, 8471, 8784, 8846, 8975, 9167, 9216, 9239, 9287, 9359, 9374, 9538, 9612, 9721, 9743, 9829, 10111, 10154, 10155, 10156, 10277, 10279, 10344, 10345, 10350, 10416, 10417, 10423, 10563, 10638, 10874, 10876], 34: [863, 983, 1268, 1458, 1486, 1813, 2100, 2201, 2218, 2243, 2370, 2392, 2411, 2418, 2423, 2615, 3074, 3162, 3347, 3358, 3408, 3503, 3566, 3624, 3636, 3874, 4098, 4163, 4165, 4196, 4208, 4593, 5199, 6271, 6397, 6490, 6649, 6675, 6736, 6781, 6926, 7020, 7037, 7093, 7298, 7319, 7488, 7888, 8318, 8375, 8509, 8575, 8616, 9047, 9173, 9299, 9431, 9456, 9791, 10055, 10088, 10176, 10276, 10376, 10439, 10522, 10589, 10617, 10619, 10708], 35: [14, 363, 796, 914, 1058, 1308, 1405, 1457, 1646, 1798, 1906, 1982, 2220, 2271, 2531, 253

In [7]:
df.groupby(['casual']).first()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,registered,count
casual,,,,,,,,,,,
0,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,1,1
1,2011-01-01 07:00:00,1,0,0,1,8.20,12.880,86,0.0000,2,3
2,2011-01-01 06:00:00,1,0,0,1,9.02,13.635,80,0.0000,0,2
3,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,13,16
4,2011-01-02 00:00:00,1,0,0,2,18.86,22.725,88,19.9995,13,17
...,...,...,...,...,...,...,...,...,...,...,...
356,2012-05-19 15:00:00,2,0,0,1,29.52,32.575,30,7.0015,316,672
357,2012-03-17 15:00:00,1,0,0,1,26.24,31.060,53,8.9981,322,679
361,2012-05-19 14:00:00,2,0,0,1,29.52,32.575,30,6.0032,369,730
362,2012-10-06 12:00:00,4,0,0,1,28.70,32.575,54,7.0015,381,743
367,2012-03-17 16:00:00,1,0,0,1,26.24,31.060,50,0.0000,318,685

In [18]:
df.groupby(['casual'])[['temp', 'atemp']].mean()

             temp      atemp
casual
0       13.821907  16.670578
1       15.903328  18.969003
2       16.297290  19.370329
3       15.845845  18.968870
4       15.762994  18.680480
...           ...        ...
356     29.520000  32.575000
357     26.240000  31.060000
361     29.520000  32.575000
362     28.700000  32.575000
367     26.240000  31.060000

[309 rows x 2 columns]

In [20]:
df.groupby(['casual', 'weather'])[['temp']].mean()

                     temp
casual weather
0      1        13.218400
       2        14.695938
       3        14.886154
1      1        15.565282
       2        15.987709
...                   ...
356    1        29.520000
357    1        26.240000
361    1        29.520000
362    1        28.700000
367    1        26.240000

[605 rows x 1 columns]

In [16]:
df.groupby(['casual']).agg({'atemp': sum, 'temp': 'first'})

            atemp   temp
casual
0       16437.190   9.84
1       12652.325   8.20
2        9433.350   9.02
3        8308.365   9.84
4        6612.890  18.86
...           ...    ...
356        32.575  29.52
357        31.060  26.24
361        32.575  29.52
362        32.575  28.70
367        31.060  26.24

[309 rows x 2 columns]

In [23]:
df.groupby(['casual']).agg({'atemp': [sum, 'mean'], 'temp': 'first'})

            atemp              temp
              sum       mean  first
casual
0       16437.190  16.670578   9.84
1       12652.325  18.969003   8.20
2        9433.350  19.370329   9.02
3        8308.365  18.968870   9.84
4        6612.890  18.680480  18.86
...           ...        ...    ...
356        32.575  32.575000  29.52
357        31.060  31.060000  26.24
361        32.575  32.575000  29.52
362        32.575  32.575000  28.70
367        31.060  31.060000  26.24

[309 rows x 3 columns]

In [27]:
df.groupby(['casual']).agg({'atemp': lambda x: max(x) + x.mean(), 'temp': 'first'})

            atemp   temp
casual
0       52.275578   9.84
1       57.604003   8.20
2       57.250329   9.02
3       54.573870   9.84
4       54.285480  18.86
...           ...    ...
356     65.150000  29.52
357     62.120000  26.24
361     65.150000  29.52
362     65.150000  28.70
367     62.120000  26.24

[309 rows x 2 columns]